---
- name: 'copy dockerhub password'
  copy:
    dest: "/home/{{ build_user }}/docker_password.txt"
    content: "{{ secret_dockerhub_user_password }}"
    mode: 0644
    owner: "{{ build_user }}"
    group: "{{ build_user }}"

# When this role is being run when using Packer on the util slave, for some unknown reason
# it isn't allowed to access the Docker daemon. This is why the ignore errors flag is set.
# The solution was to add the docker login command as a separate shell script step in the Packer
# template. This still works running it in another context, e.g. a vagrant up, so I'm leaving it
# in and setting ignore errors, rather than taking it out entirely.
- name: 'login to dockerhub for pushing images'
  shell: |
    cat docker_password.txt | docker login --username {{ dockerhub_user }} --password-stdin
  args:
    chdir: "/home/{{ build_user }}"
  become: yes
  become_user: "{{ build_user }}"
  ignore_errors: yes

- name: 'pull docker image for safe client libs'
  docker_image:
    name: "{{ safe_client_libs_build_image_name }}:{{ safe_client_libs_build_image_tag }}"
  when: docker_slave_project == 'safe_client_libs'

- name: 'pull docker image for safe_nd'
  docker_image:
    name: "{{ safe_nd_build_image_name }}:{{ safe_nd_build_image_tag }}"
  when: docker_slave_project == 'safe_nd'

- name: 'pull docker images for safe_cli'
  docker_image:
    name: "{{ safe_cli_build_image_name }}:{{ item }}"
  when: docker_slave_project == 'safe_cli'
  with_items:
    - build
    - build-dev

- name: 'pull docker image for safe_vault'
  docker_image:
    name: "{{ safe_vault_build_image_name }}:{{ safe_vault_build_image_tag }}"
  when: docker_slave_project == 'safe_vault'

- name: 'pull docker images for safe_auth_cli'
  docker_image:
    name: "{{ safe_auth_build_image_name }}:{{ item }}"
  when: docker_slave_project == 'safe_authenticator_cli'
  with_items:
    - build
